# maintainer: u1and0 <e01.ando60@gmail.com>
# version 3.7 for docker version 18.06+
# see https://docs.docker.com/compose/compose-file/
# What for:
#    docker in docker dev.env
#
#    * master: zsh & zplug env. Parents for all docker image.
#    * jupyter: python env. It can use ipython & jupyter
#    * vim-go: golang env.
#
# Usage:
#	 $ cd /path/to/composeset
#    $ docker-compose up
#    $ docker exec -it composeset_master_1 zsh -l
#
# 	 # Login master container then...
#    $ tmux
#
#    # Login go env
#    $ docker exec -it composeset_vim-go_1 zsh -l
#
#    # Login python env
# 	 $ docker exec -it composeset_jupyter_1 bash -c ". .bashrc && zsh"
#
#    # Login python env as ipython
# 	 $ docker exec -it composeset_jupyter_1 bash -c ". .bashrc && ipython"
#
version: '3'
services:

    master:
        image: "u1and0/docker:latest"
        tty: true
        volumes:
            - "${HOME}/Dropbox:/home/u1and0/Dropbox"
            - "${HOME}/.zsh_history:/home/u1and0/.zsh_history"
            - "${HOME}/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
            - "/mnt/e/Users/U1and0:/mnt"
            - "/var/run/docker.sock:/var/run/docker.sock"
        restart: "always"
        environment:
            - "HOST=master"

    jupyter:
        # jupyter tagはpasswordを設定したイメージ
        # [Jupyter on Dockerでパスワードの設定方法が分からないあなたへ](https://qiita.com/Yusuke-Shimizu/items/731ca71b3c4c3649ec7f)
        image: "u1and0/python-conda:latest"
        volumes:
            - "${HOME}/Dropbox:/home/u1and0/Dropbox"
            - "${HOME}/.zsh_history:/home/u1and0/.zsh_history"
            - "${HOME}/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
            - "/mnt/e/Users/U1and0/Dropbox:/mnt"
        environment:
            - "PYTHONPATH=/home/u1and0/Dropbox/Program/python"
            - "HOST=conda"
        command: "bash -c '. .bashrc && jupyter notebook'"
        ports:
            - "8888:8888"

    vimgo:
        # update current binary image (!! Not coded infra !!)
        image: "u1and0/vim-go:latest"
        tty: true
        volumes:
            - "${HOME}/Dropbox:/home/u1and0/Dropbox"
            - "${HOME}/.zsh_history:/home/u1and0/.zsh_history"
            - "${HOME}/yankring_history_v2.txt:/home/u1and0/yankring_history_v2.txt"
            - "/mnt/e/Users/U1and0:/mnt"
        environment:
            - "HOST=vim-go"
            - "GOPATH=/home/u1and0/go"
        working_dir: "$GOPATH"
        ports:
            - "8080:8080"
        cap_add:
            - "SYS_PTRACE" # for golang debugger

    # uplot:
    #     image: "u1and0/uplot:latest"
    #     ports:
    #         - "8880:8880"
